version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: AgileExpressMongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb

  elasticsearch:
    image: elasticsearch:7.4.2
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
    user: root

volumes:
  data:  {}

networks:
  default:
    name: mongodb_network