spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 948966529463-t79u00fn881hpvl8vqmfqmbl1mmfv7u6.apps.googleusercontent.com
            client-secret: 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
            client-name: AgileExpress
            redirect-uri: http://localhost:9000/login/oauth2/code/google

  data:
    mongodb:
      #authentication-database: admin
      #username: rootuser
      #password: rootpass
      database: AgileExpress
      #port: 27017
      #host: localhost
      uri: mongodb+srv://Rabitttt:Selman_02588520@cluster0.s2os0cs.mongodb.net/AgileExpress?retryWrites=true&w=majority